### ISSUE TITLE
Handle errors on network offline / dns resolution

### ISSUE THREAD

**Issue by ilmanzo** [ilmanzo/package_last_update#7]
when offline, now the program ends with 

```<urllib3.connection.HTTPSConnection object at 0x7fbd7cd74520>: Failed to establish a new connection: [Errno -2] Name or service not known```

Handle exception and give a more user friendly error message

**Comment by Abraham12611** [comment]
Hello 👋. I would like to contribute and help to handle the exception and provide a more user friendly error message.

As this is my very first. Please how do I go about this.

**Comment by ilmanzo** [comment]
Hello, thanks for your interest. The main idea is to give the user a useful error when the network is disconnected or the service is not reachable. There are two main places where this can happen, one is on the spawn of the external `osc` process and the other is when we directly send `requests.get` to [repology](https://repology.org/) webservice , so probably you need to wrap each one in a separate manner inside a try/except. Feel free to make a PR with a proposal, I have assigned this issue to you :)

**Comment by Abraham12611** [comment]
Okay, I would make a pull request with a proposal.

Thanks

**Comment by Abraham12611** [comment]
I have made a pull request

**Comment by ilmanzo** [comment]
looks on the good track, thanks! I'd ask also to take care of the errors when the user runs the bash script instead of the helper program.

```
./shouldIupdate.sh 
<urllib3.connection.HTTPSConnection object at 0x7f5f91dec520>: Failed to establish a new connection: [Errno -2] Name or service not known
```

this error is probably caused by the `$(osc -A https://api.opensuse.org my packages)` call

**Comment by Abraham12611** [comment]
I would look into it

**Comment by Abraham12611** [comment]
I have the second pull request.

The changes I made was to check if the "osc" command was available and also redirected the 'stderr' message to 'stdout'. Exiting the program if the message==
<urllib3.connection.HTTPSConnection object at 0x7f5f91dec520>: Failed to establish a new connection: [Errno -2] Name or service not known

**Comment by ilmanzo** [comment]
thanks for the contribution!

**Comment by Abraham12611** [comment]
I am glad I completed my first open source contribute.

Thank you for the opportunity.
